spring:
  application:
    name: gerenciador-acessos
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus

#  autoconfigure:
#    exclude:
#      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
#      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration