apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
spec:
  storageClassName: grafana
  capacity:
    storage: 400Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /home/wagner/Dev/grafana_data
  