apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-external-service
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3000
      nodePort: 30100
  type: NodePort

  