apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: gerenciador-acessos
  resources:
    requests:
      storage: 400Mi

  